name: Generate Installer ISO
on:
  workflow_dispatch:

jobs:
  build-iso:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Package Bootable ISO File
        uses: jasonn3/build-container-installer@v1.5.0
        with:
          base_registry: 'ghcr.io'
          base_image: 'rainthefur/yuri-gaming-os'
          image_tag: 'latest'
          iso_name: 'yuri-gaming-os.iso'
          version: '41'
